//
// DO NOT MODIFY version.hpp, it is automatically generated by cmake
//

#ifndef SZ3_VERSION_HPP
#define SZ3_VERSION_HPP

#define SZ3_NAME "SZ3"
#define SZ3_VER  "3.1.5.3"
#define SZ3_VER_MAJOR 3
#define SZ3_VER_MINOR 1
#define SZ3_VER_PATCH 5
#define SZ3_VER_TWEAK 3

#endif //SZ3_VERSION_HPP
